# Generated by Django 2.0.3 on 2018-04-02 14:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tropic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.CharField(blank=True, max_length=30, null=True)),
                ('blogTime', models.DateTimeField(null=True)),
                ('blogEditor', models.CharField(editable=False, max_length=50)),
                ('blogContent', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='博文内容')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标签名')),
            ],
        ),
        migrations.AddField(
            model_name='blogpage',
            name='blogTag',
            field=models.ManyToManyField(blank=True, to='tropic.Tag', verbose_name='标签集合'),
        ),
    ]
