# Generated by Django 2.0.3 on 2018-04-03 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tropic', '0002_auto_20180402_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='blogEditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
