# Generated by Django 2.0.3 on 2018-04-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tropic', '0003_auto_20180403_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccomment',
            name='imgurl',
            field=models.TextField(default='http://myest.club/static/media/city.png'),
        ),
    ]
