# Generated by Django 2.0.3 on 2018-06-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tropic', '0005_todotable'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotable',
            name='updateVersion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
